### ISSUE TITLE
Integrating Lindner-Peikert from P1

### ISSUE THREAD

**Issue by kruegers** [eclipse-cognicrypt/CogniCrypt#15]
For integration, the following things are still missing: 
1) Implementation of the algorithm in a CSP 
2) stylesheet (Editing the one for symmetric block ciphers should suffice) 
3) Some simple task for the algorithm to be used in (Encryption with a public key algorithm?, post-quantum secure?)"

**Comment by akwick** [comment]
During a meeting with JBr and P1, we decided to cancel the integration. Thus, I will close this issue.
