### ISSUE TITLE
Instances in instance list page in wrong order due to string key

### ISSUE THREAD

**Issue by abirke** [eclipse-cognicrypt/CogniCrypt#163]
#### Prerequisites
* **Git branch/Commit-ID:**  `master`

### Issue description
In `InstanceGenerator.generateInstanceMapping` the generated instances are put into a `Map<String, InstanceClafer>` which is not order-preserving. Even though the `TreeMap` that is used to initialize the map is indeed order-preserving, it uses its key (here, the instance name as a string) as a key for sorting, which leads to instances with numbers larger than 100 being misplaced.

### Suggestion
My suggestion would be to iterate over the `List<InstaceClafer> generatedInstances` field instead of the map and implement a custom ContentProvider to prevent type erros in the InstanceListPage which would be affected most by the change.

**Comment by kruegers** [comment]
With the replacement of the XSL-based code generator and the re-design of CogniCrypt_GEN's UI, this issue has become obsolte.
