### ISSUE TITLE
Design a "CogniCrypt properties" menu

### ISSUE THREAD

**Issue by kruegers** [eclipse-cognicrypt/CogniCrypt#190]
Some CogniCrypt features may be configurable by its user. Create a menu that allows for this configuration.
It should at least contain the following options:
- [x] Source of CrySL rules (drop-down menu with 'CogniCrypt-internal rules' being pre-selected)
- [x] En-/Disable automated analysis when saving
- [ ] En-/Disable automatic analysis of dependencies
- [ ] En-/Disable automatic analysis of dependencies on change (gets auto-selected when previous option is selected)

- [x] Advanced options
  - [x] Selection of call-graph construction algorithm
  - [x] ~~Selection of entry point (is only available when CHA is not selected as CG algorithm)~~
  - [x] Selection of error-marker types for each error type

**Comment by kruegers** [comment]
Assigned @shahrzadav.

**Comment by Lonzak** [comment]
Please implement this - CogniCrypt blocks my whole eclipse build process and causes nasty "hangs" where it is not possible to work anymore.

**Comment by kruegers** [comment]
Hey @Lonzak,
Feel free to check out CogniCrypt again. The preference page is not completely done yet, but the version we just deployed to the update site contains the option to turn on/off automated analyses, among others. By default, this feature is now turned off. Since @shahrzadav also implemented #188, you can also trigger the analysis from a context menu when right-clicking a project in the package explorer. We have not updated the documentation yet but will do so shortly. Ask away, should you run into any issues.
