### ISSUE TITLE
Implement feedback feature

### ISSUE THREAD

**Issue by kruegers** [eclipse-cognicrypt/CogniCrypt#195]
When CogniCrypt_SAST reports a misuse but the user is certain, the reported issue is no misuse, they should be able to report that false positive. Implement such a feature.
The option should appear when user right-clicks the error marker. A windows should appear in which there is a text field in case the user wants to describe the issue and a label informing the user the file they are in will be sent along with their description. When they click finish both the description and the source code are sent to a tbd email address.

**Comment by AndreSonntag** [comment]
![image](https://user-images.githubusercontent.com/31883471/72971139-66c30880-3dc9-11ea-8e94-312969319c4a.png)

**Comment by AndreSonntag** [comment]
Update:

Unfortunately, it is not possible to display a help text in a multi line text fields.
https://stackoverflow.com/questions/46471212/hint-on-multiline-swt-text

![image](https://user-images.githubusercontent.com/31883471/73956927-ebec0880-4905-11ea-8ca5-23674a0dce48.png)

![image](https://user-images.githubusercontent.com/31883471/73957026-12aa3f00-4906-11ea-91c4-463322e1dd29.png)

**Comment by AndreSonntag** [comment]
Update: 
![image](https://user-images.githubusercontent.com/31883471/74439739-0f1a3900-4e6d-11ea-9b4a-84bd880d5a63.png)
