### ISSUE TITLE
Show progress bar for analysis

### ISSUE THREAD

**Issue by kruegers** [eclipse-cognicrypt/CogniCrypt#196]
The analysis may be long-running. Implement a progress bar that uses the number of seeds to estimate progress.

**Comment by johspaeth** [comment]
In CogniCrypt_SAST, the [estimated analysis time](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/f40e1447b2c8debaaff8c8b47e9fb10a9176303e/CryptoAnalysis/src/main/java/crypto/analysis/CryptoScanner.java#L101) is already printed to the console.

It can be used to compute the state of the progress bar and additional time information.

**Comment by kruegers** [comment]
assigned @seena-mathew
