### ISSUE TITLE
Automatic Push of Nightly Build to Update Site

### ISSUE THREAD

**Issue by kruegers** [eclipse-cognicrypt/CogniCrypt#208]
Extend the nightly build shippable configuration such that the plugins are pushed to our update site (http://download.eclipse.org/cognicrypt/) automatically.

For information on what's currently working (or not), touch base with @CCPah. He was working on this before leaving.

**Comment by enriozuni** [comment]
@kruegers just a reminder about this issue. In the Shippable integration called Update Site (type SSH Key), try to put the public key of that integration in the Eclipse update site

**Comment by kruegers** [comment]
On hold til [transfer](https://github.com/CROSSINGTUD/CogniCrypt/issues/223#issuecomment-437661265) is done. Unassigning @enriozuni til I'm done.

**Comment by kruegers** [comment]
scp -r $folder [username]@build.eclipse.org:downloads/cognicrypt

**Comment by johspaeth** [comment]
I.e. from the root directory the correct command is

`scp -r repository/target/repository/. [username]@build.eclipse.org:downloads/cognicrypt`

*Note: Only the account who created the files can delete/update files on the update site. Therefore, only a single account can be used to control the version on the update site*

**Comment by johspaeth** [comment]
I followed this description:
https://wiki.eclipse.org/Jenkins

* [Requested write access](https://bugs.eclipse.org/bugs/show_bug.cgi?id=547091) for the Jenkins server to upload files to the update site.
* Added a Jenkinsfile that deploys the `master` branch to `<UpdateSite>/stable` and `develop` to `<UpdateSite>/snapshot`. 

Once we have write access, we have to test the deployment.

**Comment by johspaeth** [comment]
[Our Jenkins job](https://jenkins.eclipse.org/cognicrypt/job/cognicrypt-multibranch/) now automatically publishes the `master` branch to the update site 
http://download.eclipse.org/cognicrypt/stable
and `develop` to
http://download.eclipse.org/cognicrypt/snapshot

@kruegers we have to update our process accordingly. 
Also the update site still contains the last stable version from two weeks ago. Let me know when I can remove it. http://download.eclipse.org/cognicrypt/
We need to update the [doc](https://www.eclipse.org/cognicrypt/downloads/)

**Comment by kruegers** [comment]
Thanks @johspaeth for taking care of this. 
I have updated the documentation accordingly. Is there anything else that needs updating before we remove that old version and close this issue?

**Comment by johspaeth** [comment]
The only thing left is to establish a solid process.

- Keep `master` clean
- Merge first in `develop` and from time to time from `develop` to `master` 
- Throughroughly test before merge

Should we make `develop` our default branch on GitHub?

**Comment by kruegers** [comment]
As you have implemented the process as you suggested it and we do not have the rights to change the default branch in this repo, I'm closing this issue now.
