### ISSUE TITLE
Move Continuous Integration to Eclipse Jenkins

### ISSUE THREAD

**Issue by ericbodden** [eclipse-cognicrypt/CogniCrypt#220]
I would like to discuss whether to move our CI from Shippable to https://jenkins.eclipse.org

Does the current solution have any advantages?

**Comment by kruegers** [comment]
@enriozuni After you got a first prototype for the [provider detection](https://github.com/CROSSINGTUD/CogniCrypt/issues/191) working, please split your hours between the detection's improvement and this issue here. Also requires #223 to have been resolved.

**Comment by enriozuni** [comment]
@kruegers Sure

**Comment by kruegers** [comment]
Currently blocked by [this issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=544892).

**Comment by johspaeth** [comment]
I opened an additional bug report on a eclispe CI mailing list.

https://www.eclipse.org/lists/cbi-dev/msg02113.html

> On your successful build, I see:
> 
> [INFO] Building de.cognicrypt.crysl.handler 1.0.0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] Downloading from xtend: http://build.eclipse.org/common/xtend/maven/de/darmstadt/tu/crossing/CryptSL/de.darmstadt.tu.crossing.CryptSL/1.0.0-SNAPSHOT/maven-metadata.xml
> [WARNING] Checksum validation failed, expected <!doctype but is c143977810d6345b60e0d28515110a949a29a3a8 from xtend for http://build.eclipse.org/common/xtend/maven/de/darmstadt/tu/crossing/CryptSL/de.darmstadt.tu.crossing.CryptSL/1.0.0-SNAPSHOT/maven-metadata.xml
> [WARNING] Could not validate integrity of download from http://build.eclipse.org/common/xtend/maven/de/darmstadt/tu/crossing/CryptSL/de.darmstadt.tu.crossing.CryptSL/1.0.0-SNAPSHOT/maven-metadata.xml: Checksum validation failed, expected <!doctype but is c143977810d6345b60e0d28515110a949a29a3a8
> [WARNING] Checksum validation failed, expected <!doctype but is c143977810d6345b60e0d28515110a949a29a3a8 from xtend for http://build.eclipse.org/common/xtend/maven/de/darmstadt/tu/crossing/CryptSL/de.darmstadt.tu.crossing.CryptSL/1.0.0-SNAPSHOT/maven-metadata.xml
> [INFO] Downloaded from xtend: http://build.eclipse.org/common/xtend/maven/de/darmstadt/tu/crossing/CryptSL/de.darmstadt.tu.crossing.CryptSL/1.0.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 355 B/s)
> [WARNING] The metadata /var/lib/jenkins/.m2/repository/de/darmstadt/tu/crossing/CryptSL/de.darmstadt.tu.crossing.CryptSL/1.0.0-SNAPSHOT/maven-metadata-xtend.xml is invalid: unexpected markup <!d (position: START_DOCUMENT seen <!d... @1:3) 
> [WARNING] The metadata /var/lib/jenkins/.m2/repository/de/darmstadt/tu/crossing/CryptSL/de.darmstadt.tu.crossing.CryptSL/1.0.0-SNAPSHOT/maven-metadata-xtend.xml is invalid: unexpected markup <!d (position: START_DOCUMENT seen <!d... @1:3) 
> 
> Notice the Validation Failed and Unexpected Markup.
> 
> On the failed build, I see:
> [INFO] Building de.cognicrypt.crysl.handler 1.0.0-SNAPSHOT               [4/10]
> [INFO] ---------------------------[ eclipse-plugin ]---------------------------
> [DEBUG] Using transporter WagonTransporter with priority -1.0 for http://build.eclipse.org/common/xtend/maven/
> [INFO] Downloading from xtend: http://build.eclipse.org/common/xtend/maven/de/darmstadt/tu/crossing/CryptSL/de.darmstadt.tu.crossing.CryptSL/1.0.0-SNAPSHOT/maven-metadata.xml
> [WARNING] Could not transfer metadata de.darmstadt.tu.crossing.CryptSL:de.darmstadt.tu.crossing.CryptSL:1.0.0-SNAPSHOT/maven-metadata.xml from/to xtend (http://build.eclipse.org/common/xtend/maven/): eclipse.org: Name or service not known
> [WARNING] Failure to transfer de.darmstadt.tu.crossing.CryptSL:de.darmstadt.tu.crossing.CryptSL:1.0.0-SNAPSHOT/maven-metadata.xml from http://build.eclipse.org/common/xtend/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of xtend has elapsed or updates are forced. Original error: Could not transfer metadata de.darmstadt.tu.crossing.CryptSL:de.darmstadt.tu.crossing.CryptSL:1.0.0-SNAPSHOT/maven-metadata.xml from/to xtend (http://build.eclipse.org/common/xtend/maven/): eclipse.org: Name or service not known
> 
> In the end, this URL is a 404:
> 
> http://build.eclipse.org/common/xtend/maven/de/darmstadt/tu/crossing/CryptSL/de.darmstadt.tu.crossing.CryptSL/1.0.0-SNAPSHOT/maven-metadata.xml
> 
> 
> I'm not sure why that succeeds on your end, because it never gets downloaded anyway. Perhaps one build job does not fail on warnings.
> At any rate, obtaining Xtend from build.eclipse.org has to be severely outdated.
> 
> 

We have to take care of the validation. @kruegers Why do we download Xtend from build.eclipse instead of  maven central?
