### ISSUE TITLE
Error message missing blanks

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-cognicrypt/CogniCrypt#222]
I see these hard to read error messages in a project:
```
First parameter was not properly generatedKeyManager
Second parameter was not properly generatedTrustManager
```
The type name of the parameter is just added to the error message without any blank or other punctuation in between.

**Comment by kruegers** [comment]
Thanks, @Bananeweizen. 

This is an issue related to how the analysis itself constructs error messages. It should instead print "... not properly generated as Key Manager."
@rakshitkr and @sritejakv Could one of you please take care of this? You can find the code [here](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/master/CryptoAnalysis/src/main/java/crypto/analysis/errors/ConstraintError.java#L125). Fixing this should be a matter of minutes.

**Comment by johspaeth** [comment]
I guess @rakshitkr  and @sritejakv need more information about it. At the moment, the analysis prints the name of the generated predicate, which is: "generatedKeyManager". See [here](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/2c933416627983bf6b0ef65d37fdd2f532ce6cbe/src/de/darmstadt/tu/crossing/KeyManagerFactory.cryptsl#L32). 

What is the suggested logic to get from generatedKeyManager to the String "generated as Key Manager"? Are there more such cases for predicates? We should not hard-code too much here, as the predicate names are chosen arbitrarily.

**Comment by kruegers** [comment]
They aren't though (or at least: they ought not to be). The first word is always a verb in past participle. Any subsequent words are nouns that describe what the verb was affecting and begin with a capital letter. Take generatedKey. Here, the key was generated by the object under analysis. All one has to do is put in white spaces after the verb. When there is no noun, no whitespacing is necessary of course.
The code probably looks a bit like this:

String predicateName = ...;
String[] parts = splitAtCapitalLetters(predicateName);
String errorMessage = varName + " was not properly generated as " + parts[0];
for (1 til parts.length) {
 errorMessage += " " parts[i];
}
