### ISSUE TITLE
New eclipse repository is confusing

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-cognicrypt/CogniCrypt#223]
It's very confusing to have the sources available twice, once here and once at https://github.com/eclipse-cognicrypt/CogniCrypt. Also if that second URL is meant to become the new home of the project, then please recreate the repository and push the sources _including_ the history. The commit messages are extremely important during later development to understand why some code was written as it is.

**Comment by johspaeth** [comment]
Thanks for reporting, we are aware of it. We will move this repository (incl. all of the issues) to the eclipse repository. Unfortunately, we cannot maintain the complete history of the repository and have to squash it (eclipse restrictions).

**Comment by johspaeth** [comment]
The repository has been moved.
