### ISSUE TITLE
False positive for KeyStore creation scenario ("Expect call to one of....")

### ISSUE THREAD

**Issue by Lonzak** [eclipse-cognicrypt/CogniCrypt#225]
The code

```
KeyStore keyStore = KeyStore.getInstance("PKCS12");
keyStore.load(null,null);

// Add private and public key (certificate) to keystore
keyStore.setEntry("alias", new PrivateKeyEntry(...), new KeyStore.PasswordProtection(...);
keyStore.store(new FileOutputStream(...), "Password".toCharArray()); //Error
``` 
triggers the following error
> Unexpected call to method store on object of type java.security.KeyStore. Expect a call to one of the following methods **getKey,getEntry**

However the usage scenario is not loading and using an existing keystore but the creation of a new keystore and filling it with certificates/keys. So it seems like an FP to me.

**Comment by kruegers** [comment]
Hey @Lonzak,

Thanks for the issue. It should be fixed now when you pull the latest CogniCrypt version from the update site.

**Comment by Lonzak** [comment]
Thanks for the fix! I'll try it out but I need to wait for [issue 229](https://github.com/eclipse-cognicrypt/CogniCrypt/issues/229) since I thus had to uninstall cc...
