### ISSUE TITLE
CogniCrypt Analysis freezes eclipse during saving/compiling

### ISSUE THREAD

**Issue by Lonzak** [eclipse-cognicrypt/CogniCrypt#229]
My eclipse and thus the development is regularily blocked by a running CogniCrypt Analysis. Everytime I save one file or compile the whole IDE becomes unusable for several seconds (depending on how big the project is). In a bigger project this can last up-to 10-20 seconds. This is really annoying and my last resort would be to uninstall it.
Is it possible to deactivate the CogniCrypt scan? (Maybe related to https://github.com/eclipse-cognicrypt/CogniCrypt/issues/190)
But why don't you design it as an on-demand scan? Like SpotBugs/Findbugs or others? There is no reason to executa a scan on each save.

I really like your idea but this is really blocking the development.

Update: I don't have the fastest computer (an older Dual core CPU, 8GB RAM, SSD) so others with a faster setup maybe not experience it so heavily...

**Comment by johspaeth** [comment]
I observed the same issue when I imported [this project](https://github.com/CROSSINGTUD/CryptoAnalysis/tree/master/CryptoAnalysisTargets/ReportedIssues) into the workspace. I performed some profiling. By default, an Eclipse instance runs with 1024 megabyte of memory, which is too little memory to run soot and the static analysis.

To solve the issue, [increase the memory](https://stackoverflow.com/questions/4304312/max-value-of-xmx-and-xms-in-eclipse) to -Xmx4g of your eclipse instance within the [eclipse.ini](https://wiki.eclipse.org/Eclipse.ini)

**Comment by Lonzak** [comment]
My setting is on 2g and i am not able to increase it further since I have 2-3 eclipse open in parallel. Additionally a jboss and a DB is running + webbrowser and lots of other stuff. Long story short Memory is at its limit... But still there are those freezes. 

I wouldn't mind if I triggered the the run manually. But I experience it with each file save of a java class. At least provide a way to deactivate the scan...

**Comment by johspaeth** [comment]
An increase of the setting -Xmx just allows the JVM to use more memory at the time required, i.e., at analysis time. Garbage collection then automatically frees memory when the system requires more. Therefore, increasing the setting doesn't harm, it just gives you a better user experience.

Nevermind, we are working on a preference page which also allows you to enable and disable automatic analysis. 

Also feel free to contribute code to the project!

**Comment by Lonzak** [comment]
*thumbs up* for the preference page.

>Also feel free to contribute code to the project!

Yeah would like to but can't dance at too many weddings...
