### ISSUE TITLE
Rules are not converted upon Import of a Project

### ISSUE THREAD

**Issue by johspaeth** [eclipse-cognicrypt/CogniCrypt#244]
Upon importing a project containing CrySL-rules, the static analysis for these rules does not work out-of-the-box. One has to change and save the rules at least once.

Rule conversion is only triggered after a [successful build](https://github.com/eclipse-cognicrypt/CogniCrypt/blob/master/plugins/de.cognicrypt.crysl.handler/src/de/cognicrypt/crysl/handler/StartupHandler.java).

`What if we react on [POST_CHANGE](https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcore%2Fresources%2FIResourceChangeEvent.html) instead of POST_BUILD?

**Comment by kruegers** [comment]
For reference: https://www.eclipse.org/articles/Article-Builders/builders.html
