### ISSUE TITLE
Error marker types preferences do not use Eclipse wording

### ISSUE THREAD

**Issue by achelos-bel** [eclipse-cognicrypt/CogniCrypt#264]
**Describe the bug**
The error marker types on the CogniCrypt Eclipse plug-in's preference page are named differently than on other Eclipse preference pages.

**To Reproduce**
1. Open the CogniCrypt preference page.
2. Open a drop-down list in the “Error-Marker Types” section. It shows “Problem”, “Warning”, “Secure”.

**Expected behavior**
Commonly used types like “Error”, “Warning”, “Info” should be used. Compare the preference pages “Java”/“Compiler”/“Errors/Warnings”, “Maven”/“Errors/Warnings”, or “SpotBugs”. Maybe the section “Error-Marker Types” should be renamed to “Errors/Warnings”.

**Desktop (please complete the following information):**
 - Version 1.0.0.201902280326

**Comment by kruegers** [comment]
Hey @achelos-bel,
That was indeed an oversight of mine. The 'Secure' option was supposed to be named 'Info' and we also plan to include an option 'None' for no warning whatsoever. Thanks for pointing this out.

@shahrzadav Could you please fix the label in the preference page and add the 'None' label? Thanks.

**Comment by achelos-bel** [comment]
Please note that “None” is called “Ignore” on other preference pages.

**Comment by kruegers** [comment]
Works for me, too.

**Comment by shahrzadav** [comment]
@kruegers yeah sure.

**Comment by achelos-bel** [comment]
I updated to CogniCrypt 1.0.0.201903291356. The types “Warning”, “Info” are used now. But “Problem” is still used instead of “Error”.

**Comment by achelos-bel** [comment]
I updated to 1.0.0.201904151418 and the same holds as in my last comment: “Problem” instead of “Error”.

**Comment by johspaeth** [comment]
@achelos-bel It hadn't been fixed yet. I performed the renaming just now. It will be contained in the next version.

**Comment by achelos-bel** [comment]
Fixed in CogniCrypt 1.0.0.201904181142.
