### ISSUE TITLE
CogniCrypt entry is missing from Eclipse project context menu in Plug-in Development perspective

### ISSUE THREAD

**Issue by achelos-bel** [eclipse-cognicrypt/CogniCrypt#277]
**Describe the bug**
Before upgrading to the CogniCrypt Eclipse plug-in 1.0.0.201903291356, a context menu entry was available to run the analysis on a java project. After upgrading, this entry is shown only when using the Java perspective, but not when using the Plug-in Development perspective.

**Screenshots**
![Screenshot_20190411_103208](https://user-images.githubusercontent.com/46530249/55952493-0e67b380-5c5a-11e9-8586-fb5dd0e1f8f7.png)

**Desktop (please complete the following information):**
 - Eclipse 2018-12

**Comment by kruegers** [comment]
Thanks for the issue. I pushed the latest version of CogniCrypt to the website and with this one, I cannot reproduce the behaviour. Can you please update your installation and check again? If the bug is still present please let me know about your environment to enable to reproduce it.

**Comment by achelos-bel** [comment]
I updated to CogniCrypt 1.0.0.201904151418. Still, the entry is missing from the context menu in the Project Explorer view (used in the Plug-in Development perspective). It is available in the Package Explorer view. I right-clicked the same Eclipse project in both views to open the context menus.

**Comment by kruegers** [comment]
I see. I had only checked in the package explorer, not the project explorer because I'm using the former in both. It should work now. Please check and feel free to re-open the issue if the bug persists. Thanks.

**Comment by achelos-bel** [comment]
Fixed in CogniCrypt 1.0.0.201904181142.
