### ISSUE TITLE
Grid view to select multiple rule sets / API specification in Preference Page

### ISSUE THREAD

**Issue by johspaeth** [eclipse-cognicrypt/CogniCrypt#279]
Instead of a dropdown which allows the user to select a single ruleset only, the preference page shall list a grid view. The grid view allows the user to select multiple rulesets at once. By default we should enable all of them.

Example: 

Select CrySL-API specification

- [x] JCA 
- [x] BouncyCastle
- [x] Tink

In addition to the grid view, we need to tie the user input to the actual rule sets the analysis selects. The functionality must be implemented [in this line](https://github.com/eclipse-cognicrypt/CogniCrypt/blob/73c7d196f9eab0ef625b354e102467e12e742473/plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/sootbridge/SootRunner.java#L84).

Associate to each entry (API) in the grid a path (string) which is the name of the subfolder where the ruleset is located. Within the subfolder you can expect to find `.cryptslbin` files. The static analysis expects a set of CrySL rules (in form of `cryptsbin` files) which is created [here](https://github.com/eclipse-cognicrypt/CogniCrypt/blob/73c7d196f9eab0ef625b354e102467e12e742473/plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/sootbridge/SootRunner.java#L84). The set must depend on the selected API by the user within the grid. For each selected API add the respectives rules to the set.

**Comment by kruegers** [comment]
Assigned @shahrzadav . Please do this after the dependencies tho. Thanks.

**Comment by kruegers** [comment]
Assigned @rakshitkr  & @sritejakv. Is implemented through #314.
