### ISSUE TITLE
Dependency to ruleset must be on soot classpath

### ISSUE THREAD

**Issue by johspaeth** [eclipse-cognicrypt/CogniCrypt#287]
When analysing a project using BouncyCastle with the BouncyCastle rules, the findings are incorrect. 

The root cause is that libraries are not passed to Soot. Therefore the call graph at calls to a libraries are not modelled (including calls such as `new RSAEngine()`) and the analysis terminates at such.

Fix: Find the dependencies (List of locations to .jar files) of a project and hand it over to Soot. Note: The list must at least include the .jar which contain the classes of a selected ruleset.

@shahrzadav is working on a related issue, let me know once you are done.

**Comment by shahrzadav** [comment]
@johspaeth yeah, I am working on it
