### ISSUE TITLE
Crash in class CCStatement

### ISSUE THREAD

**Issue by johspaeth** [eclipse-cognicrypt/CogniCrypt#289]
When I analyze some project I got the following error:
```
java.lang.RuntimeException: getInvokeExpr() called with no invokeExpr present!
    at soot.jimple.internal.JAssignStmt.getInvokeExpr(JAssignStmt.java:130)
    at de.cognicrypt.staticanalyzer.statement.CCStatement.<init>(CCStatement.java:23)
```

and wondered if we actually need the class `CCStatement`. What is it used for? Am I right that it's pure existence is to deliver hashCode and equals method? @AndreSonntag can we remove the class once we updated to a version of CryptoAnalysis that includes the changes from your last pull request (https://github.com/CROSSINGTUD/CryptoAnalysis/pull/146)?

**Comment by AndreSonntag** [comment]
Sorry for the late answer. Indeed, the class was only for the hashCode generation. My last pull request fixed the problem.

**Comment by kruegers** [comment]
assigned @AndreSonntag
