### ISSUE TITLE
CogniCrypt fails to track static fields

### ISSUE THREAD

**Issue by ericbodden** [eclipse-cognicrypt/CogniCrypt#292]
Linghui has a test case in which the program uses too few rounds for key derivation but the round value "20" is stored in a static fields. CogniCrypt fails to report this rule violation.

**Comment by johspaeth** [comment]
Thanks for reporting @linghuiluo can you share the code?

**Comment by johspaeth** [comment]
I found minimal working and non-working code:

No error: 

	private static String INSTANCE = "AES";

	public static void main(String...args) throws GeneralSecurityException {
		Cipher cip = Cipher.getInstance(INSTANCE);
		cip.doFinal();
	}


but an error is shown when we explicitly assign the field to a variable

	private static String INSTANCE;

	public static void main(String...args) throws GeneralSecurityException {
		String var = "AES";
		INSTANCE = var;
		Cipher cip = Cipher.getInstance(INSTANCE);
		cip.doFinal();
	}

**Comment by linghuiluo** [comment]
@johspaeth example here
```  
private static int count = 20;

  public static Key foo(String text, byte[] salt) {
    try {
      char[] textCharArray = text.toCharArray();
      PBEKeySpec pbe = new PBEKeySpec(textCharArray, salt, count, 128);
      SecretKeyFactory skf;
      skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
      SecretKey key=skf.generateSecret(pbe);
      return new SecretKeySpec(key.getEncoded(), "AES");
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

````

**Comment by kruegers** [comment]
Closing this issue because it is a duplicate to CROSSINGTUD/CryptoAnalysis#97.
