### ISSUE TITLE
Usable as commandlinetool/in CICD systems

### ISSUE THREAD

**Issue by deknos** [eclipse-cognicrypt/CogniCrypt#297]
**Is your feature request related to a problem? Please describe.**
I use vim. Other use visualstudio. There are plenty of different Development Environment, perhaps i cannot use your tool in my environment. 

**Describe the solution you'd like**
i would like to have cognicrypt as a command-line-based program either for working local OR that i can use it in a CICD-Pipeline, so code is tested before it is deployed.

**Comment by johspaeth** [comment]
The analysis is available as command-line tool which is independent of Eclipse:
https://github.com/CROSSINGTUD/CryptoAnalysis
