### ISSUE TITLE
Code Generation does not work in eclipse 2019-03 (current version)

### ISSUE THREAD

**Issue by mreif** [eclipse-cognicrypt/CogniCrypt#298]
**Describe the bug**
The code generation does not work for any task. Hitting the __generate__ button leaves me with the message that no suitable configuration was found. As all tasks are affected I suspect a general CogniCrypt issue with the newest Eclipse version.

**To Reproduce**
1. Trigger CogniCrypt dialog
2. Click on any task
3. Answer configuration questions
4. Hit the generate button
5. Code generation fails with the error that there no valid configuration has been found.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.05]
 - Eclipse:
    - Version: 2019-03 (4.11.0)
    - Build id: 20190314-1200

**Additional context**
CogniCrypt was started in a freshly created Java project with exactly one class with an empty main method.

**Comment by kruegers** [comment]
Behaviour can no longer be reproduced. Neither on the original machine nor on two others.
