### ISSUE TITLE
Visualization of suppressed warnings

### ISSUE THREAD

**Issue by AndreSonntag** [eclipse-cognicrypt/CogniCrypt#302]
The user has the opportunity to suppress an error from the CryptoAnalysis
via SuppressWarning quickfix on the IDE. The quickfix stores the necessary information
in an XML file which is located in the client project. After a while, it could
happen that the user forgets that he suppressed an error.

The normal Eclipse way to show that an error or warning is suppressed is via
@SuppressWarnings("...") annotation. Every annotation is subject to certain 
targets (see https://docs.oracle.com/javase/10/docs/api/java/lang/annotation/ElementType.html).
Unfortunately, none of the target types allowed it to add an annotation to a method invocation.
That's why this way of showing a suppress warning is not suitable for us.

A new idea is to use **Warning** or **Info** marker to visualize a suppress warning.
(see https://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcore%2Fresources%2FIMarker.html)

**Comment by seena-mathew** [comment]
assigned @seena-mathew
