### ISSUE TITLE
Save Files on Analysis

### ISSUE THREAD

**Issue by AnakinRaW** [eclipse-cognicrypt/CogniCrypt#304]
In the (current) version 1.0.0.201905151726 triggering the code analysis should automatically save all dirty files. Otherwise users might experience that an error marker will get miss placed and do not match the code finding.

**Comment by kruegers** [comment]
Thanks Sebastian for the suggestion.
After an internal discussion, we decided to do the following:
CogniCrypt checks if the file that is currently opened in the Eclipse editor is saved or dirty. In the latter case, a message pops up and asks whether the file should be saved. All other files are left untouched.

**Comment by shahrzadav** [comment]
assigned @shahrzadav
