### ISSUE TITLE
Build error for the submodule de.cognicrypt.core

### ISSUE THREAD

**Issue by sritejakv** [eclipse-cognicrypt/CogniCrypt#306]
**Describe the bug**
Following error is being thrown in the console when CogniCrypt is built with maven. A log file is attached for more details.

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.26.0:compile (default-compile) on project de.cognicrypt.core: Compilation failure: Compilation failure: 
[ERROR] /Users/rakshitkr/git/SHK/CogniCrypt/plugins/de.cognicrypt.core/src/de/cognicrypt/utils/Utils.java: 
[ERROR] 	/********************************************************************************
[ERROR] 	^
[ERROR] The type org.eclipse.swt.widgets.Composite cannot be resolved. It is indirectly referenced from required .class files
[ERROR] 1 problem (1 error)

**To Reproduce**
1. Go to 'root folder of CogniCrypt'
2. Run 'mvn clean install -DskipTests'
3. See error

**Expected behavior**
The build should be successfully executed.

[build_log_txt.txt](https://github.com/eclipse-cognicrypt/CogniCrypt/files/3442866/build_log_txt.txt)

**Comment by kruegers** [comment]
Thanks for fixing this.
