### ISSUE TITLE
Better Exception Handling

### ISSUE THREAD

**Issue by AnakinRaW** [eclipse-cognicrypt/CogniCrypt#336]
This issue is highly dependent on [the CryptoAnalysis Exception Issue #198](https://github.com/CROSSINGTUD/CryptoAnalysis/issues/198)

In general improve the way how CogniCrypt is handling failures

- [ ]  Revise all current exceptions and replace them if necessary. Especially replace JRE exclusive exceptions like `ClassNotFoundException` or `RuntimeException`

also we could think of (if not already discussed) how to deal with exceptions and errors. Are there some Eclipse functionalities we could use for handling exceptions? I could imagine something like:

- Safe fallbacks if a exception was not caught at the right place --> The IDE must noch crash under all circumstances
- Automatically log errors/exceptions from CogniCrypt including class file, source line, stack trace, relevant variable data
- Message boxes (or other UI features) to inform what happened.

**Comment by enriozuni** [comment]
Assigned to @enriozuni
