### ISSUE TITLE
No findings for package-private embedded classes

### ISSUE THREAD

**Issue by AnakinRaW** [eclipse-cognicrypt/CogniCrypt#337]
Consider the following example: 

A package private class is inside a source file that belongs to a public class:

```java
// File: Main.java
package com.example.test;

import java.security.*;
import javax.crypto.Cipher;

public class Main {
	public static void main(String[] args) throws GeneralSecurityException {
		System.out.println("Hello World");
		Crypto.CreateCipher();
	}
}

class Crypto{
	public static void CreateCipher() throws GeneralSecurityException {
		Cipher c = Cipher.getInstance("DES");
		c.doFinal();
	}	
}
// EOF: Main.java
```

The eclipse plugin is unable to find the misuse in the package private class `Crypto`. As far as I can tell CryptoAnalysis however finds the issue. So my guess is (as with the Kotlin issue) the plugin cannot create a mapping between the Crypto.class file and the Main.java file and thus is unable to present the finding to the user.

**Comment by enriozuni** [comment]
Assigned @enriozuni
