### ISSUE TITLE
Preference page of CogniCrypt is not displayed

### ISSUE THREAD

**Issue by shahrzadav** [eclipse-cognicrypt/CogniCrypt#348]
**Describe the bug**
I have the latest update of the CogniCrypt plugin installed on my eclipse, when I open the preference page and go to CogniCrypt I face an error and it does not show any options of CogniCrypt preferences.

**To Reproduce**
1. Go to 'Eclipse'
2. Click on 'Window' tab
3. Click on  'Preferences'
4. Click on 'CogniCrypt'

**Expected behavior**
it is expected to see options in CogniCrypt preference page without facing any errors.

**Screenshots**

<img width="428" alt="issue-preferencepage" src="https://user-images.githubusercontent.com/7203009/69856292-98b66380-128d-11ea-8931-df8c6546c35d.PNG">

 - OS: Windows 10
 - Eclipse:  2018-12 (4.10.0)

**Comment by kruegers** [comment]
Can't reproduce with the latest version of CC. Please try again and update here.
