### ISSUE TITLE
Load local CrySL rules

### ISSUE THREAD

**Issue by AnakinRaW** [eclipse-cognicrypt/CogniCrypt#413]
**Is your feature request related to a problem? Please describe.**
**Context 1:** I have seen companies with strict network rules, not being able to download the latest CrySL rules. In fact, the settings screen where you can select versions, is blanc here. 
**Context 2:** If we are developing CrySL rules we might want to test them directly in the IDE. 

**Describe the solution you'd like**
In the CogniCrypt Settings there already is a button to add new rules, but it only allows to enter a URL. Beside that it is unclear which kind of URL we are expecting here (hard link to a file, some special nexus path, etc...), we should also allow to enter file system paths to directories where CrySL rules are located. Once added a local path it should also appear in the list, so you can uncheck them.

**Comment by enriozuni** [comment]
This issue can be closed.
